import Stack from "@mui/material/Stack";
import CHART_CONFIG from "./chart_config";

export const report_config = {
  sections: [
    {
      id: "section_urgent-basic-needs",
      title: "Urgent and Basic Needs",
      tables: [
        {
          id: "table_urgent-basic-needs-main",
          layout: "two-columns",
          rows: [
            {
              key: "CIRG-PHQ9",
              source: "cnics",
              comparison: "higher",
              comparisonToAlert: "higher",
              instrumentName: "PHQ-9",
              lastAssessed: "2025-05-11",
              maxScore: 27,
              meaning: "severe depression",
              score: 23,
              alert: true,
              scoringParams: {
                maximumScore: 27,
                minimumScore: 24,
                highScore: 20,
                scoreSeverity: "high",
              },
              totalAnswered: 9,
              totalItems: 9,
              chartData: {
                ...CHART_CONFIG.default,
                maximumScore: 27,
                minimumScore: 24,
                highScore: 20,
                chartHeight: 250,
                xLabel: "",
                id: "PHQ9_Chart",
                title: "PHQ9",
                data: CHART_CONFIG.default.dataFormatter([
                  {
                    date: "2025-05-11",
                    total: 23,
                    source: "cnics", // TODO get it from real data source
                  },
                  {
                    date: "2024-09-11",
                    total: 20,
                    source: "epic",
                  },
                  {
                    date: "2023-08-08",
                    total: 16,
                    source: "cnics",
                  },
                  {
                    date: "2023-01-08",
                    total: 12,
                    source: "cnics",
                  },
                ]),
              },
            },
            {
              key: "CIRG-PHQ9-SI",
              source: "cnics",
              comparison: "higher",
              comparisonToAlert: "",
              instrumentName: "Suicide Ideation",
              lastAssessed: "2025-05-11",
              maxScore: 3,
              meaning: "Nearly Every Day",
              alert: true,
              minScore: 0,
              score: 3,
              totalAnswered: 1,
              scoringParams: {
                maximumScore: 3,
                minimumScore: 1,
                scoreSeverity: "high",
                highScore: 3,
              },
              chartData: {
                ...CHART_CONFIG.default,
                id: "PHQ_SI_CHART",
                title: "Suicide Ideation",
                type: "linechart",
                maximumScore: 3,
                minimumScore: 1,
                highScore: 3,
                xLabel: "",
                data: CHART_CONFIG.default.dataFormatter([
                  {
                    date: "2025-05-11",
                    total: 3,
                    source: "cnics",
                  },
                  {
                    date: "2024-09-11",
                    total: 2,
                    source: "epic",
                  },
                  {
                    date: "2023-08-08",
                    total: 2,
                    source: "cnics",
                  },
                  {
                    date: "2023-01-08",
                    total: 1,
                    source: "cnics",
                  },
                ]),
              },
            },
            {
              key: "CIRG-Overdose",
              comparison: "",
              comparisonToAlert: "",
              instrumentName: "Overdose (recent)",
              lastAssessed: "2025-05-11",
              meaning: "Yes",
              text: "",
              alert: true,
              totalAnswered: 1,
              source: "cnics",
            },
            {
              key: "CIRG-IPV",
              comparison: "",
              comparisonToAlert: "",
              instrumentName: "IPV (past year)",
              lastAssessed: "2025-05-11",
              meaning: "No",
              text: "",
              totalAnswered: 1,
              source: "cnics",
            },
            {
              key: "CIRG-Food-Security",
              comparison: "",
              comparisonToAlert: "",
              instrumentName: "Food Security",
              lastAssessed: "2025-05-11",
              meaning: "Very Low Food Security",
              text: "",
              alert: true,
              totalAnswered: 1,
              source: "cnics",
            },
            {
              key: "CIRG-Financial-Situation",
              comparison: "",
              comparisonToAlert: "",
              instrumentName: "Financial Situation",
              lastAssessed: "2025-05-11",
              meaning: "Struggling to Survive",
              text: "",
              alert: true,
              totalAnswered: 1,
              source: "cnics",
            },
          ],
        },
      ],
    },
    {
      id: "section_symptoms",
      title: "Symptoms",
      tables: [
        {
          id: "table_symptoms-bother",
          layout: "simple",
          hiddenColumns: ["id", "source", "lastAssessed", "score", "numAnswered", "meaning", "comparison"],
          columns: [
            {
              id: "measure",
              header: "Measure",
              align: "left",
              accessor: "measure",
              headerProps: { sx: { textAlign: "left", backgroundColor: "lightest.main" } },
            },
            { id: "bothersALot", header: "Bothers a lot", align: "right", accessor: "bothersALot" },
            { id: "bothersSome", header: "Bothers some", align: "right", accessor: "bothersSome" },
          ],
          rows: [
            {
              id: 1,
              measure: "Current Symptoms",
              bothersALot: "Rash, Cough",
              bothersSome: "Sad, Headache",
              source: "cnics",
            },
          ],
        },
      ],
    },
    {
      id: "section_health_behaviors",
      title: "Health Behavior",
      tables: [
        {
          id: "table_art_adherence",
          layout: "simple",
          title: "ART Adherence",
          hiddenColumns: ["id", "source", "lastAssessed", "score", "numAnswered", "meaning", "comparison"],
          columns: [
            {
              id: "measure",
              header: "Measure",
              align: "left",
              accessor: "measure",
              type: "text",
              headerProps: { sx: { textAlign: "left", backgroundColor: "lightest.main" } },
            },
            {
              id: "lastMissedDose",
              header: "Last Missed Dose",
              align: "left",
              accessor: "lastMissedDose",
              type: "text",
            },
          ],
          rows: [{ id: 22, measure: "Last Missed Dose", lastMissedDose: "Within the last week", source: "cnics" }],
        },
        {
          id: "table_substance_use",
          title: "Substance Use",
          layout: "two-columns",
          rows: [
            {
              key: "CIRG-Nicotine-Use",
              source: "cnics",
              comparison: "",
              comparisonToAlert: "",
              instrumentName: "Nicotine Use",
              lastAssessed: "2025-05-11",
              meaning: "Tobacco cigarettes: Currently",
              text: "N/A",
              totalAnswered: 1,
            },
            {
              key: "CIRG-Alcohol-Use",
              source: "cnics",
              comparison: "higher",
              comparisonToAlert: "",
              instrumentName: "Alcohol Score",
              lastAssessed: "2025-05-11",
              maxScore: 45,
              meaning: "At Risk",
              minScore: 0,
              score: 40,
              alert: true,
              scoringParams: {
                maximumScore: 3,
                minimumScore: 1,
                scoreSeverity: "high",
                highScore: 35,
              },
              totalAnswered: 10,
              totalItems: 10,
              chartData: {
                ...CHART_CONFIG.default,
                id: "Alcohol_Use_CHART",
                title: "Alcohol Score",
                type: "barchart",
                maximumScore: 45,
                minimumScore: 0,
                highScore: 35,
                xLabel: "",
                data: CHART_CONFIG.default.dataFormatter([
                  {
                    date: "2025-05-11",
                    total: 40,
                    source: "cnics",
                  },
                  {
                    date: "2024-09-11",
                    total: 35,
                    source: "cnics",
                  },
                  {
                    date: "2023-08-08",
                    total: 25,
                    source: "cnics",
                  },
                  {
                    date: "2023-01-08",
                    total: 20,
                    source: "cnics",
                  },
                ]),
              },
            },
            {
              key: "CIRG-Mini-Score",
              source: "cnics",
              comparison: "higher",
              comparisonToAlert: "",
              instrumentName: "MINI Score",
              lastAssessed: "2025-05-11",
              maxScore: 5,
              meaning: "Dependent Drinker",
              minScore: 0,
              score: 3,
              scoringParams: {
                maximumScore: 5,
                minimumScore: 1,
                highScore: 4,
              },
              totalAnswered: 3,
              totalItems: 3,
              chartData: {
                ...CHART_CONFIG.default,
                id: "MINI_Score_CHART",
                title: "MINI Score",
                maximumScore: 5,
                minimumScore: 0,
                highScore: 4,
                xLabel: "",
                data: CHART_CONFIG.default.dataFormatter([
                  {
                    date: "2025-05-11",
                    total: 3,
                  },
                  {
                    date: "2024-09-11",
                    total: 3,
                  },
                  {
                    date: "2023-08-08",
                    total: 2,
                  },
                  {
                    date: "2023-01-08",
                    total: 2,
                  },
                ]),
              },
            },
            {
              key: "CIRG-Concurrent-Drug-Use",
              source: "cnics",
              comparison: "",
              comparisonToAlert: "",
              instrumentName: "Concurrent Drug Use",
              lastAssessed: "2025-05-11",
              meaning: "No",
              text: "N/A",
              totalAnswered: 1,
            },
          ],
        },
        {
          id: "table_sexual_risk",
          layout: "simple",
          title: "Sexual Risk Behavior",
          // columns: [
          //   { field: "measure", headername: "Measure", type: "text" },
          //   { field: "date", headername: "Last Done", type: "text" },
          //   { field: "result", headername: "Result", type: "text" },
          // ],
          hiddenColumns: ["id", "source", "lastAssessed", "score", "numAnswered", "meaning", "comparison"],
          columns: [
            {
              id: "measure",
              header: "Measure",
              align: "left",
              accessor: "measure",
              type: "text",
              headerProps: { sx: { textAlign: "left", backgroundColor: "lightest.main" } },
            },
            {
              id: "result",
              header: "Result",
              align: "left",
              accessor: "result",
              type: "text",
            },
            {
              id: "date",
              header: "Last Done",
              align: "left",
              accessor: "date",
              type: "text",
              renderCell: (row, value) => (
                <Stack direction={"column"} spacing={1}>
                  <span>{value ?? "--"}</span>
                  {row.source && <span className="muted-text">{row.source}</span>}
                </Stack>
              ),
            },
          ],
          rows: [
            { id: 23, measure: "# of sex partners x 3 months", result: "2", date: "2025-05-11", source: "cnics" },
            { id: 24, measure: "Unprotected sex", result: "Yes", date: "2025-05-11", source: "cnics" },
            { id: 25, measure: "Exchange sex (recent)", result: "No", date: "2025-05-11", source: "cnics" },
            { id: 26, measure: "Concern for STI", result: "No", date: "2025-05-11", source: "cnics" },
          ],
        },
        {
          id: "table_psychosocial_concern",
          layout: "simple",
          title: "Psychosocial Concerns and Quality of Life",
          // columns: [
          //   { field: "measure", headername: "Measure", type: "text" },
          //   { field: "date", headername: "Most Recent PRO Date", type: "text" },
          //   { field: "result", headername: "Result", type: "text" },
          // ],
          hiddenColumns: ["id", "source", "lastAssessed", "score", "numAnswered", "meaning", "comparison"],
          columns: [
            {
              id: "measure",
              header: "Measure",
              align: "left",
              accessor: "measure",
              type: "text",
              headerProps: { sx: { textAlign: "left", backgroundColor: "lightest.main" } },
            },
            {
              id: "result",
              header: "Result",
              align: "left",
              accessor: "result",
              type: "text",
            },
            {
              id: "date",
              header: "Last Done",
              align: "left",
              accessor: "date",
              type: "text",
              renderCell: (row, value) => (
                <Stack direction={"column"} spacing={1}>
                  <span>{value ?? "--"}</span>
                  {row.source && <span className="muted-text">{row.source}</span>}
                </Stack>
              ),
            },
          ],
          rows: [
            { id: 30, measure: "PTSD Symptoms", result: "N/A", date: "2025-05-11", source: "cnics" },
            { id: 31, measure: "Social Support", result: "N/A", date: "2025-05-11", source: "cnics" },
          ],
        },
      ],
    },
  ],
};
